In [1]:
import numpy as np

X_OR = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y_truth = np.array([[0, 1, 1, 1]]).T

In [106]:
np.random.seed(1)
synapse_0 = np.random.random((3, 1))
synapse_0

array([[  4.17022005e-01],
       [  7.20324493e-01],
       [  1.14374817e-04]])

In [107]:
def sigmoid(x):
    return(1 / (1 + np.exp(-x)))

In [108]:
def sigmoid_der(output):
    return (output * (1 - output))

In [109]:
Y_truth

array([[0],
       [1],
       [1],
       [1]])

In [114]:
for i in range(1000):
    layer_1 = sigmoid(np.dot(X_OR, synapse_0))
    #layer_1 = pre_layer_1.sum(axis=1).T
    #layer_1 = sigmoid(layer_1).reshape(4,1)
    error = Y_truth - layer_1
    layer_1_delta = error * sigmoid_der(layer_1)
    #layer_1_delta = layer_1_delta.sum(axis=0)
    #print(layer_1_delta)
    #print(X_OR)
    #print(synapse_0)
    synapse_0 += np.dot(X_OR.T, layer_1_delta) * 0.1
#layer_1
#layer_1_delta

In [115]:
layer_1

array([[ 0.04966219],
       [ 0.96894322],
       [ 0.96894225],
       [ 0.99994631]])