In [5]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did we miss the target value?
    l2_error = y - l2
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = np.dot(l2_delta, syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    if (j% 10000) == 0:
        #print("Error:" + str(np.mean(np.abs(l2_error))))
        print("l2_delta: ", l2_delta)
        #print("l2_delta: ", l1.T)
    syn1 += np.dot(l1.T, l2_delta)
    syn0 += np.dot(l0.T, l1_delta)


[[-0.00451385]
 [-0.00669325]
 [-0.00676932]
 [-0.00455133]] [[ 0.44856632  0.28639589  0.40795614  0.25371248]
 [ 0.51939863  0.32350963  0.62674606  0.42628115]
 [ 0.45968497  0.31236398  0.23841622  0.14321233]
 [ 0.59156505  0.51538526  0.49377636  0.41732254]] [[-0.11810546]
 [ 0.12769844]
 [ 0.11316304]
 [-0.13508831]]
[[-0.00451385]
 [-0.00669325]
 [-0.00676932]
 [-0.00455133]] [[ 0.44856632  0.28639589  0.40795614  0.25371248]
 [ 0.51939863  0.32350963  0.62674606  0.42628115]
 [ 0.45968497  0.31236398  0.23841622  0.14321233]
 [ 0.59156505  0.51538526  0.49377636  0.41732254]] [[-0.11810546]
 [ 0.12769844]
 [ 0.11316304]
 [-0.13508831]]
[[-0.00451385]
 [-0.00669325]
 [-0.00676932]
 [-0.00455133]] [[ 0.44856632  0.28639589  0.40795614  0.25371248]
 [ 0.51939863  0.32350963  0.62674606  0.42628115]
 [ 0.45968497  0.31236398  0.23841622  0.14321233]
 [ 0.59156505  0.51538526  0.49377636  0.41732254]] [[-0.11810546]
 [ 0.12769844]
 [ 0.11316304]
 [-0.13508831]]
[[-0.00451385]
 [-0