In [13]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
			[1],
			[1],
			[0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(60000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did we miss the target value?
    l2_error = y - l2
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)
    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = np.dot(l2_delta, syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)
    
    if (j% 10000) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
        print("l2_delta: ", l1)
        #print("l2_delta: ", l1.T)
    syn1 += np.dot(l1.T, l2_delta)
    syn0 += np.dot(l0.T, l1_delta)


Error:0.496410031903
l2_delta:  [[ 0.44856632  0.51939863  0.45968497  0.59156505]
 [ 0.28639589  0.32350963  0.31236398  0.51538526]
 [ 0.40795614  0.62674606  0.23841622  0.49377636]
 [ 0.25371248  0.42628115  0.14321233  0.41732254]]
Error:0.00858452565325
l2_delta:  [[  6.39794692e-01   1.37097918e-01   9.17995038e-01   9.94721470e-01]
 [  2.05869639e-01   6.35412465e-04   1.84354882e-02   8.85392478e-01]
 [  9.90358451e-01   8.73947201e-01   2.50298778e-02   7.89794557e-01]
 [  9.37468194e-01   2.69966253e-02   4.30709360e-05   1.33471161e-01]]
Error:0.00578945986251
l2_delta:  [[  6.76071621e-01   1.28168162e-01   9.21470647e-01   9.95877626e-01]
 [  1.88772093e-01   5.21962936e-04   1.76602176e-02   8.90030167e-01]
 [  9.93442489e-01   8.83064272e-01   2.38921162e-02   8.11403421e-01]
 [  9.44105922e-01   2.61256437e-02   3.74994886e-05   1.25978836e-01]]
Error:0.00462917677677
l2_delta:  [[  6.95576716e-01   1.23557365e-01   9.23295634e-01   9.96399633e-01]
 [  1.80042185e-01  